apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-travel-app
  namespace: adk-travel
  labels:
    app: adk-travel
    tier: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adk-travel
  template:
    metadata:
      labels:
        app: adk-travel
        tier: application
    spec:
      serviceAccountName: adk-agents
      containers:
      - name: adk-travel
        # Imagem única construída do root Dockerfile com código de src/
        image: REGION-docker.pkg.dev/PROJECT_ID/adk-travel/adk-travel-app:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: GOOGLE_CLOUD_LOCATION
          value: "REGION"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        # ADK specific settings
        - name: ADK_VERSION
          value: "1.0"
        - name: AI_PLATFORM_REGION
          value: "REGION"
        - name: MODEL_NAME
          value: "gemini-pro"
        # ConfigMap reference
        envFrom:
        - configMapRef:
            name: adk-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: adk-travel-service
  namespace: adk-travel
  labels:
    app: adk-travel
spec:
  selector:
    app: adk-travel
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adk-config
  namespace: adk-travel
data:
  GOOGLE_CLOUD_PROJECT: "PROJECT_ID"
  GOOGLE_CLOUD_LOCATION: "REGION"
  ADK_VERSION: "1.0"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  # AI Platform settings
  AI_PLATFORM_REGION: "REGION"
  MODEL_NAME: "gemini-pro"
  # Feature flags
  FLIGHT_AGENT_ENABLED: "true"
  HOTEL_AGENT_ENABLED: "true"
  ACTIVITY_AGENT_ENABLED: "true"