apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flight-agent-hpa
  namespace: adk-travel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flight-agent
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-agent-hpa
  namespace: adk-travel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotel-agent
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: travel-coordinator-hpa
  namespace: adk-travel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: travel-coordinator
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70