apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-coordinator
  namespace: adk-travel
  labels:
    app: travel-coordinator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-coordinator
  template:
    metadata:
      labels:
        app: travel-coordinator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: adk-agents
      containers:
      - name: travel-coordinator
        image: gcr.io/PROJECT_ID/travel-coordinator:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8090
          name: metrics
        env:
        - name: FLIGHT_AGENT_URL
          value: "http://flight-agent"
        - name: HOTEL_AGENT_URL
          value: "http://hotel-agent"
        - name: ACTIVITY_AGENT_URL
          value: "http://activity-agent"
        - name: METRICS_PORT
          value: "8090"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: travel-coordinator
  namespace: adk-travel
  labels:
    app: travel-coordinator
spec:
  selector:
    app: travel-coordinator
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 8090
    targetPort: 8090
    name: metrics
  type: LoadBalancer